### ISSUE TITLE
Build fails with icu 68.2-1

### ISSUE THREAD

**Issue by mpietruschka** [kisli/vmime#247]
![2021-01-04 14_55_54-github-pietmacom-kopano-pkgbuilds #209 Console  Jenkins](https://user-images.githubusercontent.com/447353/103542979-10e25600-4e9e-11eb-90af-9d60c9f7f65e.png)

**Comment by vincent-richard** [comment]
Fixed, thanks!

**Comment by mpietruschka** [comment]
thanks to you! 👍  :)

**Comment by mpietruschka** [comment]
Hej Vincent,

You forgot about updating one line for the latest icu...

https://github.com/pietmacom/vmime/commit/9116feac76a47d141679cede6fb4ccd4878e9984
